name: cdt_client
description: "Frontend app for [CDT project](https://github.com/users/a-givertzman/projects/15)"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hmi_core:
    git:
      url: https://github.com/a-givertzman/hmi_core.git
      ref: 2.1.6
  hmi_networking:
    git:
      url: https://github.com/a-givertzman/hmi_networking.git
      ref: 1.1.6
  hmi_widgets:
    git:
      url: https://github.com/a-givertzman/hmi_widgets.git
      ref: 1.3.1
  ext_rw:
    git:
      url: https://github.com/a-givertzman/dart_ext_rw.git
      ref: 1.2.4
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/settings/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
